language: python
python:
    - "3.6"
services:
    - docker

install:
    - pip install -q -r requirements.txt
    - docker build -t search-psn .
# Continuação do Script

script:
# - script para executar os testes da aplicação, por exemplo: python tests.py ou
    - pytest
